### ISSUE TITLE
Revive?

### ISSUE THREAD

**Issue by Bobbyjoness** [kikito/passion#2]
This game engine is 5 years old but looking over the ideas and api design in this engine I think it would fit perfectly in 0.10.0. I feel as though many users would use this engine if it was updated. And I was wondering of maybe you can update this to 0.10.0? I say 0.10.0 because that is the newest version and it would take awhile for you to get passion to a good place for release by then 0.10.0 should be ready.

**Comment by kikito** [comment]
I decided not to revive this project, and have marked it as deprecated and unmaintained in the README. Sorry it took me a while to treat this issue :)
